plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.team_3'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    }

dependencies {
    // WEB
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // WEB-FLUX
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // LOMBOK
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    // AWS TRANSCRIBE
    implementation platform('software.amazon.awssdk:bom:2.31.8')
    implementation 'software.amazon.awssdk:transcribe'
    implementation 'software.amazon.awssdk:transcribestreaming'

    // AWS S3
    implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.3.0")
    implementation 'io.awspring.cloud:spring-cloud-aws-starter'
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'

    // POSTGRESQL
    implementation 'org.postgresql:postgresql'
    implementation 'org.hibernate:hibernate-spatial:6.6.15.Final'

    // COOLSMS
    implementation "net.nurigo:sdk:4.3.2"

    // REDIS
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // TEST
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

