FROM openjdk:21-jdk-slim

WORKDIR /app

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG AWS_BUCKET_NAME
ARG AWS_REGION
ARG BUSINESS_AUTHENTICITY_PATH
ARG BUSINESS_AUTHENTICITY_SERVICE_KEY
ARG BUSINESS_AUTHENTICITY_URL
ARG COOLSMS_API_KEY
ARG COOLSMS_API_SECRET
ARG COOLSMS_PHONE_NUMBER
ARG RDB_USERNAME
ARG RDB_PASSWORD
ARG RDB_ENDPOINT
ARG RDB_PORT
ARG RDB_NAME
ARG REDIS_PORT
ARG REDIS_PRIVATE_IPV4
ARG JWT_ENCODING_KEY
ARG JWT_ACCESS_EXPIRATION_TIME
ARG JWT_REFRESH_EXPIRATION_TIME
ARG JWT_ENCODING_KEY
ARG JWT_ACCESS_EXPIRATION_TIME
ARG JWT_REFRESH_EXPIRATION_TIME

ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}
ENV BUSINESS_AUTHENTICITY_PATH=${BUSINESS_AUTHENTICITY_PATH}
ENV BUSINESS_AUTHENTICITY_SERVICE_KEY=${BUSINESS_AUTHENTICITY_SERVICE_KEY}
ENV BUSINESS_AUTHENTICITY_URL=${BUSINESS_AUTHENTICITY_URL}
ENV COOLSMS_API_KEY=${COOLSMS_API_KEY}
ENV COOLSMS_API_SECRET=${COOLSMS_API_SECRET}
ENV COOLSMS_PHONE_NUMBER=${COOLSMS_PHONE_NUMBER}
ENV RDB_USERNAME=${RDB_USERNAME}
ENV RDB_PASSWORD=${RDB_PASSWORD}
ENV RDB_ENDPOINT=${RDB_ENDPOINT}
ENV RDB_PORT=${RDB_PORT}
ENV RDB_NAME=${RDB_NAME}

ENV REDIS_PRIVATE_IPV4=${REDIS_PRIVATE_IPV4}
ENV REDIS_PORT=${REDIS_PORT}

ENV JWT_ENCODING_KEY=${JWT_ENCODING_KEY}
ENV JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME}
ENV JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}
ENV JWT_ENCODING_KEY=${JWT_ENCODING_KEY}
ENV JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME}
ENV JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}

COPY build/libs/nursing_care-0.0.1-SNAPSHOT.jar /app/nursing-care.jar

CMD ["java", "-jar", "/app/nursing-care.jar"]