FROM openjdk:21-jdk-slim

WORKDIR /app

ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG AWS_BUCKET_NAME
ARG AWS_REGION

ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}

COPY build/libs/nursing_care-0.0.1-SNAPSHOT.jar /app/nursing-care.jar

CMD ["java", "-jar", "/app/nursing-care.jar"]